### ISSUE TITLE
Provide a modern theme with the app package

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/roundcube_ynh#11]
It was suggested here https://dev.yunohost.org/issues/361 that a better default theme could be provided

e.g. this theme : 

![roundcube](https://user-images.githubusercontent.com/4533074/29746204-bc57f33e-8ad2-11e7-9001-ea6d51273b03.jpg)

**Comment by ericgaspar** [comment]
Closing. The 1.5.0 will bring dark theme 👀
