### ISSUE TITLE
SSO and Login failed

### ISSUE THREAD

**Issue by OK76** [YunoHost-Apps/roundcube_ynh#121]
Hi,
since the last update I cannot login with the Yunohost SSO and the login failed too with the shown login-dialog from roundcube. How can I fix? I have installed roundcube again, the same problem.

Thanks.

**Comment by OK76** [comment]
The installation directly in the console with the "fix"-brunch works. What ist wrong wih the master?

**Comment by ericgaspar** [comment]
Should be fixed in master
