### ISSUE TITLE
Upgrade to 1.5.2 failed

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/roundcube_ynh#135]
### Describe the bug

Upgrade to 1.5.2 from 1.5.0 failed

### Context

- Hardware: *VPS bought online .*
- YunoHost version: 4.3.5
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

- *Upgrade via webadmin*

### Expected behavior

*Upgrade succeeded*

### Logs

https://paste.yunohost.org/raw/ibedujijar

**Comment by kyljys** [comment]
+1

Log:
https://paste.yunohost.org/raw/gabuwurali

**Comment by isAAAc** [comment]
same issue as https://github.com/YunoHost-Apps/roundcube_ynh/issues/126

**Comment by Gredin67** [comment]
same issue for upgrade from 1.5.1 to 1.5.2 https://paste.yunohost.org/raw/ixiweqavap
`Creating database schema... ERROR: [1050] Table 'collected_contacts' already exists`

**Comment by Gredin67** [comment]
same issue for upgrade from 1.5.1 to 1.5.2 https://paste.yunohost.org/raw/ixiweqavap
`Creating database schema... ERROR: [1050] Table 'collected_contacts' already exists`

**Comment by Gredin67** [comment]
same issue for upgrade from 1.5.1 to 1.5.2 https://paste.yunohost.org/raw/ixiweqavap
`Creating database schema... ERROR: [1050] Table 'collected_contacts' already exists`

**Comment by ericgaspar** [comment]
duplicate of #126
