### ISSUE TITLE
javascript dependencies are not installed automatically

### ISSUE THREAD

**Issue by SuNounix** [YunoHost-Apps/roundcube_ynh#153]
### Describe the bug

*no "new_user_dialog", can't edit parameters and CSRF error when try to logout*

### Context

- YunoHost version: 11.0.9.9
- Roundcube version : master branch, 1.6.0~ynh1
- Fresh install

### Steps to reproduce

Just a roundcube fresh install...

### Solution

Install dependencies manually :
- `cd /var/www/roundcube`
- `sudo -u roundcube bin/install-jsdeps.sh`

**Comment by ericgaspar** [comment]
Fixed with #155
