### ISSUE TITLE
Enigma plugin : wrong Keys directory adress in config.inc.php

### ISSUE THREAD

**Issue by Cellophile** [YunoHost-Apps/roundcube_ynh#156]
Hi !
I've 3 instances of roundcube on a server, with enigma plugin for each one.
But when I went to the interface, parameters / pgp keys, I had an error about unknown Keys directory.
But  `/var/www/roundcube/plugins/enigma/home` exists. 

the problem is, for other installations than the first, the path of this directory isn't roundcube, but roundcube__2, roundcube__3, ...
And in the `/var/www/roundcube/plugins/enigma/config.inc.php` file, `$config['enigma_pgp_homedir'] = '/var/www/roundcube/plugins/enigma/home';` isn't modify during installation. So for the others installations, enigma calls always the roundcube folder instead of roundcube__2, __3, ...

**Comment by ericgaspar** [comment]
@Cellophile thanks for reporting. Can you tell use more about your YunoHost version?

**Comment by ericgaspar** [comment]
#159 should fix the issue.
