### ISSUE TITLE
Installation theme issue

### ISSUE THREAD

**Issue by rodinux** [YunoHost-Apps/roundcube_ynh#204]
### Describe the bug

fresh roundcube installation has some sort of theme issue

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.13
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: 1.6.7~ynh1

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install roundcube
    ```

### Expected behavior

*Install roundcube, open the page login with correct css ans js theme.*

### Logs

No logs important found. But we have a discussion on the forum with this bug: https://forum.yunohost.org/t/roundcube-installation-issues/29840/8

The login page is unreadeable

![Capture d’écran du 2024-06-05 10-25-26](https://github.com/YunoHost-Apps/roundcube_ynh/assets/11272759/cb7acf3f-9a25-4dfe-94fe-102c9d3e51af)

It seems permissions are not the same on some app working...

Comparing files permissions on both servers :

Wrong display

```
ls -l
total 3252
drwxrwx---  2 roundcube www-data    4096 19 mai   09:20 bin
-rw-rw----  1 roundcube www-data  213791 19 mai   09:20 CHANGELOG.md
-rw-r-----  1 root      root        1213  4 juin  18:45 composer.json
-rw-rw----  1 roundcube www-data    1086 19 mai   09:20 composer.json-dist
-rw-r--r--  1 root      root      123446  4 juin  18:45 composer.lock
-rwxr-xr-x  1 root      root     2834111  4 juin  18:43 composer.phar
drwxrwx---  2 roundcube www-data    4096  4 juin  18:52 config
-rw-rw----  1 roundcube www-data   11201 19 mai   09:20 index.php
-rw-rw----  1 roundcube www-data   12661 19 mai   09:20 INSTALL
drwxrwx---  3 roundcube www-data    4096 19 mai   09:20 installer
-rw-rw----  1 roundcube www-data    3973 19 mai   09:20 jsdeps.json
-rw-rw----  1 roundcube www-data   35147 19 mai   09:20 LICENSE
drwxrwx---  2 roundcube www-data    4096 19 mai   09:20 logs
-rw-rw----  1 roundcube www-data    4526 19 mai   09:20 Makefile
drwxrwx--- 39 roundcube www-data    4096  4 juin  18:45 plugins
drwxrwx---  8 roundcube www-data    4096 19 mai   09:20 program
drwxrwx---  3 roundcube www-data    4096 19 mai   09:20 public_html
-rw-rw----  1 roundcube www-data    3853 19 mai   09:20 README.md
-rw-rw----  1 roundcube www-data     967 19 mai   09:20 SECURITY.md
drwxrwx---  4 roundcube www-data    4096  4 juin  18:51 skins
drwxrwx---  7 roundcube www-data    4096 19 mai   09:20 SQL
drwxrwx---  3 roundcube www-data    4096  4 juin  18:45 temp
drwxrwx---  7 roundcube www-data    4096 19 mai   09:20 tests
-rw-rw----  1 roundcube www-data    4657 19 mai   09:20 UPGRADING
drwxr-xr-x 21 root      root        4096  4 juin  18:45 vendor
```
Correct display

```
ls -l
total 3256
drwxrwx---  2 roundcube www-data    4096 May 19 08:20 bin
-rw-rw----  1 roundcube www-data  213791 May 19 08:20 CHANGELOG.md
-rw-r-----  1 roundcube www-data    1212 May 20 16:57 composer.json
-rw-rw----  1 roundcube www-data    1086 May 19 08:20 composer.json-dist
-rw-r-----  1 roundcube www-data  123446 May 20 16:57 composer.lock
-rwxr-xr-x  1 root      root     2834111 May 20 16:57 composer.phar
drwxrwx---  2 roundcube www-data    4096 May 20 16:57 config
-rw-rw----  1 roundcube www-data   11201 May 19 08:20 index.php
-rw-rw----  1 roundcube www-data   12661 May 19 08:20 INSTALL
drwxrwx---  3 roundcube www-data    4096 May 19 08:20 installer
-rw-rw----  1 roundcube www-data    3973 May 19 08:20 jsdeps.json
-rw-rw----  1 roundcube www-data   35147 May 19 08:20 LICENSE
drwxrwx---  2 roundcube www-data    4096 May 19 08:20 logs
-rw-rw----  1 roundcube www-data    4526 May 19 08:20 Makefile
drwxrwx--- 39 roundcube www-data    4096 May 19 08:20 plugins
drwxrwx---  8 roundcube www-data    4096 May 19 08:20 program
drwxrwx---  3 roundcube www-data    4096 May 19 08:20 public_html
-rw-rw----  1 roundcube www-data    3853 May 19 08:20 README.md
-rw-rw----  1 roundcube www-data     967 May 19 08:20 SECURITY.md
drwxrwx---  3 roundcube www-data    4096 May 19 08:20 skins
drwxrwx---  7 roundcube www-data    4096 May 19 08:20 SQL
drwxrwx---  3 roundcube www-data    4096 May 19 08:20 temp
drwxrwx---  7 roundcube www-data    4096 May 19 08:20 tests
-rw-rw----  1 roundcube www-data    4657 May 19 08:20 UPGRADING
drwxr-x--- 16 roundcube www-data    4096 May 20 16:57 vendor
```
Here the console errors on firefox

![Capture d’écran du 2024-06-05 10-48-12](https://github.com/YunoHost-Apps/roundcube_ynh/assets/11272759/37425fb5-337d-4962-bd88-61435ec7dc29)

**Comment by DeMiro5001** [comment]
I see the same console errors here too
https://github.com/YunoHost-Apps/piwigo_ynh/issues/127

And I also have a malformed display of both apps. Not sure where to investigate

**Comment by MadMan247** [comment]
I believe that the console errors for the YNH portal is referring specifically to the tile that appears in some apps in the bottom corner allowing you to quickly access other apps, and I believe it to be unrelated to the issue at hand. But that's just a theory.
![image](https://github.com/YunoHost-Apps/roundcube_ynh/assets/54383546/d87cd8a5-12d3-4bb2-80b1-8dbbf062e244)
e.g. same error on archivebox installation that does not have malformed wepage. However, no ynh portal square.
![image](https://github.com/YunoHost-Apps/roundcube_ynh/assets/54383546/3f82d8ba-d51d-4779-8a29-d88a4d46cbd9)

**Comment by DeMiro5001** [comment]
I have it disabled before installing any of these apps.

**Comment by e-jim** [comment]
Same issue here. 
As [advised on the forum](https://forum.yunohost.org/t/affichage-casse-de-roundcube/29794/4), I installed the old larry theme:
```
# cd /var/www/roundcube/skins
# git clone https://github.com/roundcube/larry
# chown -R roundcube:www-data larry
# nano ../config/config.inc.php (and replacing elastic by larry in this config file)
```
It worked as a workaround.

**Comment by M3R14M** [comment]
I went for an updated [Elastic-based theme](https://github.com/seb1k/Elastic2022) instead of Larry, and it works like a charm. Really did not want to go back to Larry after being used to Elastic for so long.

```
# cd /var/www/roundcube/skins
# git clone https://github.com/seb1k/Elastic2022.git
# chown -R roundcube:www-data Elastic2022
# nano ../config/config.inc.php
```
last line in config:  
```php
// skin name: folder from skins/
$config['skin'] = 'Elastic2022';
```

**Comment by MadMan247** [comment]
Any chance that the composer files being owned by root have something to do with this [commit](https://github.com/YunoHost-Apps/roundcube_ynh/commit/13c37556c01be3fb124662d4dd0ee69244b2f4fd)? `export COMPOSER_ALLOW_SUPERUSER=1`, 
From install log:
 ```
2024-07-12 14:32:46,954: DEBUG - + php8.1 /var/www/roundcube/composer.phar install --no-dev -d /var/www/roundcube --no-interaction --no-ansi
2024-07-12 14:32:47,208: DEBUG - Composer plugins have been disabled for safety in this non-interactive session. Set COMPOSER_ALLOW_SUPERUSER=1 if you want to allow plugins to run as root/super user.
2024-07-12 14:32:47,209: DEBUG - Do not run Composer as root/super user! See https://getcomposer.org/root for details
2024-07-12 14:32:47,404: DEBUG - No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
```

However, the elastic theme did work properly on the prior version with this commit (from January 2024 to May 2024), so maybe not.

**Comment by e-jim** [comment]
I think the issue comes from this commit: https://github.com/YunoHost-Apps/roundcube_ynh/commit/dccb989e9d4334bb040e88677321dd387a3604f0#diff-06ac558c9cfca9e31a9a235f18d98e6d0c3bfee8bee0088108a29f2c60b318e3

You see that the source of code used is the archive of the github repo instead of the release file. I guess that the CI/CD prepares the packages more specifically than just archiving the repo. 

Anyway, I forked the repo, changed the source to the release of version 1.6.7 and it worked as expected on my Yunohost instance.
I'm sending a PR right away.
