### ISSUE TITLE
Baïkal and SMTP doesn't work anymore

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/roundcube_ynh#28]
Hi,

I can't figure out what may be the issue, but Roundcube looks broken on my server:

I can't search for contacts:
> [23-Feb-2018 22:00:12 Europe/Berlin] Failed to connect to mondomaine.fr port 443: Connexion terminée par expiration du délai d'attente
> [23-Feb-2018 22:00:12 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Httpful\Exception\ConnectionErrorException' with message 'Unable to connect to "https://mondomaine.fr:443/baikal/dav.php/addressbooks/jibec/default/": 7 Failed to connect to mondomaine.fr port 443: Connexion terminée par expiration du délai d'attente' in /var/www/roundcube/vendor/nategood/httpful/src/Httpful/Request.php:1028
> 

I can't send emails:
> 23-Feb-2018 22:10:17 +0100]: <pbslhbso> SMTP Error: Connection failed: Failed to connect socket: Connexion terminée par expiration du délai d'attente in /var/www/roundcube/program/lib/Roundcube/rcube.php on line 1667 (POST /webmail/?_task=mail&_unlock=loading1519420157470&_lang=fr_FR&_framed=1&_action=send)

My server works fine with Thunderbird and k9mail...

**Comment by Jibec** [comment]
this was related to a weird dnsmasq issue... Using `dig` showed the IP was wrong.

If fixed it with:
`sudo yunohost service regen-conf dnsmasq`

But had to force it, because it said I manually changed my settings (which is wrong, but I assume it is related to pihole which I removed weeks ago, kind ping to @maniackcrudelis if he wish to investigate this hypothesis)

**Comment by maniackcrudelis** [comment]
The only modification about dnsmasq by Pihole is here https://github.com/YunoHost-Apps/pihole_ynh/blob/master/scripts/remove#L117.
Which is cleaned by the remove script. But it's tool late to know if there was anything else.
