### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/roundcube_ynh#36]
Hi

The installation is failing. Similar issue for phpmyadmin https://github.com/YunoHost-Apps/phpmyadmin_ynh/issues/70

Log for roundcube:

```
 exec_composer /var/www/roundcube install --no-dev
+ local workdir=/var/www/roundcube
+ shift 1
+ COMPOSER_HOME=/var/www/roundcube/.composer
+ php /var/www/roundcube/composer.phar install --no-dev -d /var/www/roundcube --quiet --no-interaction
Warning: Your requirements could not be resolved to an installable set of packages.
Warning: Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
+ ynh_die 'Unable to update Roundcube core dependencies'
+ echo 'Unable to update Roundcube core dependencies'
+ exit 1
+ ynh_exit_properly
+ local exit_code=1
+ '[' 1 -eq 0 ']'
+ trap '' EXIT
+ set +eu
+ echo -e '!!\n  roundcube'\''s script has encountered an error. Its execution was cancelled.\n!!'
+ type -t ynh_clean_setup
+ ynh_die
```

**Comment by kmkaplan** [comment]
I had the same problem. Installing a couple of packages beforehand solves this:
````
apt-get install php-gd php-mbstring

**Comment by anmol26s** [comment]
@kmkaplan 
What is your YunoHost version and architecture of the hardware?

**Comment by kmkaplan** [comment]
Intel(R) Atom(TM) CPU N2800   @ 1.86GHz
```
root@pot:~# yunohost --version
yunohost: 
  repo: stable
  version: 3.0.0.1
yunohost-admin: 
  repo: stable
  version: 3.0.0
moulinette: 
  repo: stable
  version: 3.0.0
ssowat: 
  repo: stable
  version: 3.0.0

**Comment by anmol26s** [comment]
Try to install dependencies manually and check package is giving the trouble.

`apt-get install php7.0-cli php7.0-common php7.0-intl php7.0-json php7.0-mcrypt php-pear php-auth-sasl php-mail-mime php-patchwork-utf8 php-net-smtp php-net-socket php-net-ldap2 php-net-ldap3 php-zip`
 
Try this : 
`apt-get install php7.0-gd php7.0-mbstring`

**Comment by kmkaplan** [comment]
@anmol26s There is a misunderstanding: I commented here to say that for me `apt-get install php-gd php-mbstring` is the solution to the error `Warning: Your requirements could not be resolved to an installable set of packages.` that occurs while installing Roundcube. I have no trouble after installing php-gd and php-mbstring.

**Comment by anmol26s** [comment]
My bad, ` php-gd php-mbstring `should be added in the dependencies.
Thanks for clarifying.

**Comment by JimboJoe** [comment]
Fixed by https://github.com/YunoHost-Apps/roundcube_ynh/pull/42, thanks to @anmol26s :+1:
