### ISSUE TITLE
Missing `server' JVM ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/roundcube_ynh#40]
Not sure what the hell is happening but during a roundcube upgrade : 

```
Setting up ca-certificates-java (20161107~bpo8+1) ...
Error: missing `server' JVM at `/usr/lib/jvm/java-8-openjdk-armhf/jre/lib/arm/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
```

c.f. : https://forum.yunohost.org/t/mise-a-jour-roundcube-impossible/4979
and https://arnauld.org/zerobin/?840cf8a8aa97dfb9#mOcYGGeCSsYT4gIFg1lse8Wm9Ok6vigPvsEhh4nAiyY=

**Comment by JimboJoe** [comment]
Question answered on the forum. It was related to some packages badly installed before roundcube installation... hence it had nothing to do with roundcube :innocent:

**Comment by alexAubin** [comment]
Cool, thanks for investigating ! :+1:
