### ISSUE TITLE
Roundcube : plugin CardDAV  [YunoHost] [EN/FR]

### ISSUE THREAD

**Issue by Guillermo25000** [YunoHost-Apps/roundcube_ynh#46]
Good afternoon, (sorry for my bad english. French below).

I want to set up Roundcube on my Yunohost (raspberry pi) because i find more feature on this app than other.
I only have a problem. When i install it on my server i tick the case to add plugin CardDAV. At this way all is fine.
But when i go to the app and try to connect my CardDAV nextcloud it appear a green banner that say it's ok. But when i go to my Contact it's not working.
Do you have some idea to fix it ?

____________________________________________________________

Bonjour,

J’essaie d'installer Roundcube sur Yunohost (heberger sur un Rapsberry Pi). Cette application correspond à mes besoins mais j'ai un petit problème avec un plugin.
Lorsque j'installe l'application je choisis également l'installation du plugin CardDAV. Tout se passe bien.

J'ouvre mon application afin de la configurer et lorsque j'ajoute le carnet d'adresse un message m'indique que c'est opérationnel. Le seul ennuis c'est qu'en allant dans les contacts, je me rends compte que justement ce n'est pas opérationnel, le carnet n'apparait pas.

Avez vous une idée pour que cela fonctionne à nouveau ?

Merci à vous
Thanks a lot for you're reading

**Comment by angarod** [comment]
J'ai le même soucis sur une installation stock avec Nextcloud et Roundcube.

**Comment by rosbeef** [comment]
@Guillermo25000 as tu installé un serveur de cardav ? le script d'install de yunohost supporte owncloud nextcloud et baikal.
Je suis aussi dans le meme cas que vous. le plugin caldav apparait mais ne trouve pas mon calendrier par defaut.

**Comment by angarod** [comment]
C'est depuis corrigé pour moi

**Comment by ericgaspar** [comment]
Should be fixed with #97
