### ISSUE TITLE
Add "elastic" design to roundcube

### ISSUE THREAD

**Issue by lfuelling** [YunoHost-Apps/roundcube_ynh#51]
Hi,
first of all, I think this is related to #44 (but can also be handled separately).

Roundcube now has a design called "elastic" that looks really great on desktop browsers and (as opposed to the old "larry"-theme) it even works great on mobile devices like smartphone or tablets.

It would be super-cool to have this theme available in the yunohost-roundcube package. It would be even better if it was default (or there was a preference to make it default/change the default theme from yunohost-admin).

Here's a screenshot of the "compose" view on mobile (to have proof that it looks great):
![screenshot_2019-02-12_17-20-16](https://user-images.githubusercontent.com/5144843/52650443-8def3580-2eea-11e9-88e5-017c5ca925dc.png)

**Comment by Christophe31** [comment]
elastic theme is in it but not as default.

**Comment by rosbeef** [comment]
Should be nice to set it by default. i think lots of people will be more interested in its flat design.

**Comment by ericgaspar** [comment]
Closing. The 1.5.0 will bring dark theme 👀
