### ISSUE TITLE
Install failed on testing

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/roundcube_ynh#6]
Roundcube fails on testing because the temp directory is [set by root](https://github.com/YunoHost-Apps/roundcube_ynh/blob/master/scripts/install#L45), and after that, composer is [executed with admin](https://github.com/YunoHost-Apps/roundcube_ynh/blob/master/scripts/_common.sh#L91).

So, admin has not enought right access to work.

**Comment by NicolasPetton** [comment]
I also face the same issue on YNH 2.6.

**Comment by magikcypress** [comment]
If you want, you can try this version that is not totally upgraded

https://github.com/magikcypress/roundcube_ynh

**Comment by redvoodoochild** [comment]
Same Here, with YHN 2.6.4

**Comment by magikcypress** [comment]
@redvoodoochild Can you send a log for this problem ? Thank

**Comment by redvoodoochild** [comment]
Well, Now I can't : i've installed the version you posted above : 
https://github.com/magikcypress/roundcube_ynh
And it's working like a charm.

The error was that composer could'nt be installed.
Regards

**Comment by maniackcrudelis** [comment]
Fixed by https://github.com/YunoHost-Apps/roundcube_ynh/pull/13

**Comment by NicolasPetton** [comment]
@maniackcrudelis awesome, thanks!
