### ISSUE TITLE
Composer should self-update itself during upgrade script

### ISSUE THREAD

**Issue by opi** [YunoHost-Apps/roundcube_ynh#64]
See a full failing upgrade log https://paste.yunohost.org/raw/esiyuhokak

After manual upgrade of /var/www/roundcube/composer.phar the upgrade run without issue.

**Comment by maniackcrudelis** [comment]
How did you upgrade composer.phar ?

**Comment by opi** [comment]
`cd /var/www/roundcube` and the following script https://getcomposer.org/download/

I previously tried to run `/var/www/roundcube/composer.phar self-upgrade` but run into an issue, probably because my composer is too old, don't know
