### ISSUE TITLE
Installation fails because of code.jquery.com has expired certificate. 

### ISSUE THREAD

**Issue by paulslaby** [YunoHost-Apps/roundcube_ynh#82]
Hello, 
I know it is not your problem, but I hope, you can help me. I just tried to install my first yunohost app - roundcube. It failed with
```
2020-05-31 14:38:45,034: WARNING - ERROR: Failed to download source file from https://code.jquery.com/jquery-3.4.1.min.js
2020-05-31 14:38:45,589: ERROR - Could not install roundcube: An error occurred inside the app installation script
``` 
When I try from my server `curl https://code.jquery.com/jquery-3.4.1.min.js` I get `curl: (60) SSL certificate problem: certificate has expired`. My system time is in sync with real time. 
How can I add --insecure to this fetch? Or better, how to fix the issue with invalid cert?

**Comment by jsonoctopus** [comment]
You can try with the wget --no-check-certificate option. Curl might have a similar option. Apart from that you can inform the hoster of the file about the expired SSL certificate.

**Comment by paulslaby** [comment]
Yes, when I do `curl https://code.jquery.com/jquery-3.4.1.min.js -k`, it works, but how to do that during the installation process?

**Comment by jsonoctopus** [comment]
You could move /usr/bin/curl to /usr/bin/curl-real and then make a shell script in your $PATH called curl that calls "/usr/bin/curl-real -k" for the moment.
I've also checked their website https://jquery.com/download/ The download works fine in a browser. Their SSL cert is valid till October 2020.

**Comment by paulslaby** [comment]
Good idea! Thank you, it worked... I am worried a bit, but thank you :)
